---
linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/gucio321/tic-tac-go
  govet:
    check-shadowing: true
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - revive

run:
  timeout: 5m
  skip-dirs:
    - .github
    - build
    - web

issues:
  max-same-issues: 0
  exclude-use-default: false
